
NDefines.NCountry.REINFORCEMENT_DELIVERY_SPEED_MIN = 0.066	 
NDefines.NCountry.REINFORCEMENT_EQUIPMENT_DELIVERY_SPEED = 0.066
NDefines.NCountry.REINFORCEMENT_MANPOWER_DELIVERY_SPEED = 2.6	
NDefines.NCountry.REINFORCEMENT_MANPOWER_CHUNK = 0.07					
NDefines.NMilitary.REINFORCEMENT_REQUEST_MAX_WAITING_DAYS = 35
NDefines.NMilitary.REINFORCEMENT_REQUEST_DAYS_FREQUENCY = 20   
NDefines.NSupply.SUPPLY_PATH_MAX_DISTANCE = 70
NDefines.NSupply.RAILWAY_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.65
NDefines.NSupply.TRUCK_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.01
NDefines.NSupply.NAVAL_DISTANCE_FACTOR_FOR_REINFORCEMENT_SPEED = 0.06
NDefines.NAI.DEPLOY_MIN_EQUIPMENT_SURRENDER_FACTOR = 0.8 